---
dist: xenial
addons:
  apt:
    packages:
      - nodejs
      - npm
      - graphviz

sudo: required

language: java
jdk: openjdk8

cache:
  directories:
  - $HOME/.m2
  - /usr/local/lib/node
  - /usr/local/lib/node_modules

before_install:
  - sudo npm install -g decktape

after_success:
  - decktape -s 1200x900 --slides 1-500 reveal "file:///${TRAVIS_BUILD_DIR}/target/generated-slides/index.html?fragments=true" slides.pdf
  - cd target/generated-slides
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "${GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
